version: '3.3'
services:
  
  senzing-webapp:
    image: senzing/entity-search-web-app:${SENZING_DOCKER_IMAGE_VERSION_ENTITY_SEARCH_WEB_APP:-latest}
    container_name: senzing-webapp
#    command: "start:docker"
#    depends_on:
#      - senzing-api-server
    environment:
      SENZING_API_SERVER_URL: "http://senzing-api-server:8250"
      SENZING_WEB_SERVER_ADMIN_AUTH_MODE: NONE
      SENZING_WEB_SERVER_URL: "http://senzing-webapp:8251"
      SENZING_WEB_SERVER_PORT: 8251
      SENZING_WEB_SERVER_API_PATH: '/api'
      SENZING_CONSOLE_SERVER_URL: 'ws://senzing-webapp-console:8273'

    networks:
      - sz-api-network
#    volumes:
#      - '/app/node_modules'
    ports:
      - 8251:8251
      - 8255:8255

    restart: 'always'

  senzing-webapp-console:
      image: senzing/entity-search-web-app-console
      container_name: senzing-webapp-console
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        SENZING_CONSOLE_SERVER_PORT: 8273

      networks:
        - sz-api-network
      ports:
        - '8273:8273'
        - '4203:4200'
      restart: 'no'

networks:
  sz-api-network: